# Generated by Django 4.1.6 on 2023-02-13 01:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poco',
            name='data_perfu',
        ),
        migrations.RemoveField(
            model_name='poco',
            name='equipament',
        ),
        migrations.RemoveField(
            model_name='poco',
            name='profundida',
        ),
        migrations.RemoveField(
            model_name='poco',
            name='proprietar',
        ),
        migrations.AddField(
            model_name='poco',
            name='data_perfuracao',
            field=models.DateField(blank=True, null=True, verbose_name='data de perfuração'),
        ),
        migrations.AddField(
            model_name='poco',
            name='equipamento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='equipamento'),
        ),
        migrations.AddField(
            model_name='poco',
            name='profundidade',
            field=models.FloatField(blank=True, null=True, verbose_name='profundidade (m)'),
        ),
        migrations.AddField(
            model_name='poco',
            name='proprietario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='proprietário'),
        ),
        migrations.AlterField(
            model_name='poco',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='geom'),
        ),
        migrations.AlterField(
            model_name='poco',
            name='orgao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='órgão responsável'),
        ),
        migrations.AlterField(
            model_name='poco',
            name='q_m3h',
            field=models.FloatField(blank=True, null=True, verbose_name='vazão m3/h'),
        ),
    ]
